# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: HOME
    url: /#home
    weight: 10
  - name: LAB MEMBERS
    url: people
    weight: 30
  - name: RESEARCH
    url: research
    weight: 40
  - name: PUBLICATION
    url: publication
    weight: 50
  - name: RESOURCE
    url: resource
    weight: 55
  # - name: Join Us!
  #   url: joinus
  #   weight: 60
  - name: CONTACT
    url: contact
    weight: 70